# Generated by Django 5.2.3 on 2025-08-01 16:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('instrucciones', models.TextField(help_text='Instrucciones de uso del área')),
                ('cupos_por_horario', models.PositiveIntegerField(default=1, help_text='Número de cupos disponibles por horario', validators=[django.core.validators.MinValueValidator(1)])),
                ('horarios_permitidos', models.JSONField(default=dict, help_text='Horarios permitidos por día de la semana')),
                ('duraciones_permitidas', models.JSONField(default=list, help_text='Lista de duraciones permitidas en horas [1, 2, 3, 4]')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Área Común',
                'verbose_name_plural': 'Áreas Comunes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_departamento', models.CharField(max_length=10)),
                ('es_administrador', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pacifik', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], default='reservado', max_length=20)),
                ('terminos_aceptados', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='pacifik.area')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_pacifik', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha', '-horario_inicio'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'reservado')), fields=('usuario', 'area', 'fecha', 'horario_inicio'), name='unique_reservation_per_user_area_date_time')],
            },
        ),
    ]
