# Generated by Django 5.2.3 on 2025-06-25 17:07

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='hero/')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('boton_texto', models.CharField(blank=True, max_length=50)),
                ('link', models.URLField(blank=True, verbose_name='Enlace destino')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Para ordenar los slides')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('posicion', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='team/')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('resumen', models.TextField()),
                ('cuerpo', models.TextField()),
                ('imagen', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='noticias/')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liga', models.CharField(blank=True, max_length=100, null=True)),
                ('equipo_rival', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('logo_visitante', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='logos_visitantes/')),
                ('goles_local', models.PositiveSmallIntegerField(default=0, verbose_name='Goles Tumbes FC')),
                ('goles_visitante', models.PositiveSmallIntegerField(default=0, verbose_name='Goles rival')),
                ('goleadores_local', models.CharField(blank=True, max_length=250, verbose_name='Goleadores Tumbes FC')),
                ('goleadores_visitante', models.CharField(blank=True, max_length=250, verbose_name='Goleadores rival')),
                ('finalizado', models.BooleanField(default=False, verbose_name='¿Ya jugado?')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='sponsors/')),
                ('url', models.URLField(verbose_name='Sitio web o red social')),
                ('destacado', models.BooleanField(default=False, verbose_name='¿Sponsor influyente?')),
            ],
        ),
    ]
