# Generated by Django 5.2.3 on 2025-06-26 04:28

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Imagen destacada para el artículo.', null=True, storage=storages.backends.s3.S3Storage(), upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto profesional de la psicóloga.', null=True, storage=storages.backends.s3.S3Storage(), upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen representativa del servicio.', null=True, storage=storages.backends.s3.S3Storage(), upload_to='service_images/'),
        ),
    ]
