# Generated by Django 5.2.3 on 2025-06-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology_api', '0002_alter_post_featured_image_alter_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='whatsapp_message',
            field=models.TextField(blank=True, help_text='Mensaje predeterminado de WhatsApp para este servicio. Si se deja en blanco, no habrá mensaje.'),
        ),
        migrations.AddField(
            model_name='service',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Número de WhatsApp específico para este servicio (ej. 51947208124). Si se deja en blanco, se usará el número por defecto.', max_length=20),
        ),
    ]
