# Generated by Django 5.2.3 on 2025-06-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology_api', '0003_service_whatsapp_message_service_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_whatsapp_number', models.CharField(blank=True, help_text='El número de WhatsApp principal que se usará en toda la web.', max_length=20)),
                ('default_whatsapp_message', models.TextField(blank=True, help_text='El mensaje predeterminado de WhatsApp que se usará en toda la web.')),
            ],
        ),
    ]
