# Generated by Django 5.2.3 on 2025-06-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology_api', '0004_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='URL completa de la página de Facebook.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='URL completa del perfil de Instagram.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='URL completa del perfil de TikTok.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='URL completa del canal de YouTube.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Número de WhatsApp específico para este servicio (ej. 51948362849). Si se deja en blanco, se usará el número por defecto.', max_length=20),
        ),
    ]
