# Generated by Django 5.2.3 on 2025-07-04 17:05

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology_api', '0005_sitesettings_facebook_url_sitesettings_instagram_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del libro', max_length=200)),
                ('slug', models.SlugField(help_text='Versión amigable para URL, ej: mi-libro-digital', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Descripción o sinopsis del libro.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio de venta del libro.', max_digits=10)),
                ('author', models.CharField(blank=True, help_text='Autor del libro, si no eres tú.', max_length=100)),
                ('cover_image', models.ImageField(help_text='Imagen de portada del libro.', storage=storages.backends.s3.S3Storage(), upload_to='book_covers/')),
                ('pdf_file', models.FileField(help_text='Archivo PDF del libro (se mantendrá privado).', storage=storages.backends.s3.S3Storage(), upload_to='book_pdfs/')),
                ('is_published', models.BooleanField(default=True, help_text='Marcar para que el libro sea visible en la tienda.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
