# Generated by Django 5.2.3 on 2025-07-07 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology_api', '0006_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text='Asociar con un usuario de Django para la psicóloga', on_delete=django.db.models.deletion.CASCADE, related_name='psychology_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
