# Generated by Django 5.2.3 on 2025-06-30 19:43

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articuloblog',
            name='imagen_destacada',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='blog_images/'),
        ),
    ]
