# Generated by Django 5.2.3 on 2025-07-05 21:22

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='avatars/'),
        ),
    ]
