# Generated by Django 5.2.3 on 2025-07-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_profile_facebook_url_profile_instagram_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram_username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tiktok_username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='x_username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('generic', 'Genérico'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('x', 'X (Twitter)'), ('facebook', 'Facebook')], default='generic', max_length=20),
        ),
    ]
