# Generated by Django 5.2.3 on 2025-07-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_profile_background_image_profile_custom_gradient_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='button_color',
            field=models.CharField(blank=True, help_text='Color de fondo del botón, ej: #000000', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='button_style',
            field=models.CharField(blank=True, help_text='Ej: rounded, squared, outline', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='button_text_color',
            field=models.CharField(blank=True, help_text='Color del texto del botón, ej: #FFFFFF', max_length=7, null=True),
        ),
    ]
