# Generated by Django 5.2.3 on 2025-07-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_profile_button_color_profile_button_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_links',
            field=models.JSONField(blank=True, help_text='Enlaces personalizados en formato JSON', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_links',
            field=models.JSONField(blank=True, help_text='Enlaces a redes sociales en formato JSON', null=True),
        ),
    ]
