# Generated by Django 5.2.3 on 2025-07-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_profile_custom_links_profile_social_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='link',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Para ordenar los enlaces'),
        ),
    ]
