# Generated by Django 5.2.3 on 2025-07-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0010_alter_link_options_link_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='custom_links',
        ),
    ]
