# Generated by Django 5.0.6 on 2024-07-09 03:15

from django.db import migrations

def migrate_social_links_to_link_model(apps, schema_editor):
    """
    Migra los datos del campo JSON `social_links` del modelo Profile
    a nuevos objetos en el modelo Link.
    """
    Profile = apps.get_model('links', 'Profile')
    Link = apps.get_model('links', 'Link')

    for profile in Profile.objects.all():
        # El campo social_links ya no existe en el modelo, pero sí en el estado
        # de la base de datos en este punto de la migración.
        # Usamos getattr para acceder a él de forma segura.
        social_links_data = getattr(profile, 'social_links', None)

        if social_links_data and isinstance(social_links_data, dict):
            for platform, url in social_links_data.items():
                if url and url.strip():  # Asegurarse de que la URL no esté vacía
                    # Crear un nuevo objeto Link para cada red social
                    Link.objects.create(
                        profile=profile,
                        title=platform.capitalize(),  # ej. 'Instagram'
                        url=url,
                        type=platform,  # ej. 'instagram'
                        # El 'order' se puede ajustar si es necesario
                    )

class Migration(migrations.Migration):

    dependencies = [
        ('links', '0011_remove_profile_custom_links'),
    ]

    operations = [
        migrations.RunPython(migrate_social_links_to_link_model, reverse_code=migrations.RunPython.noop),
    ]