# Generated by Django 5.2.3 on 2025-07-08 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0012_migrate_social_links_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_links',
        ),
    ]
