# Generated by Django 5.2.3 on 2025-07-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0013_remove_social_links_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='button_text_opacity',
            field=models.FloatField(default=1.0, help_text='Opacidad del texto del botón (0.0 a 1.0)'),
        ),
    ]
