# Generated by Django 5.2.3 on 2025-07-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0014_profile_button_text_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='button_background_opacity',
            field=models.FloatField(default=1.0, help_text='Opacidad del fondo del botón (0.0 a 1.0)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='button_border_color',
            field=models.CharField(blank=True, help_text='Color del borde del botón, ej: #000000', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='button_border_opacity',
            field=models.FloatField(default=1.0, help_text='Opacidad del borde del botón (0.0 a 1.0)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='button_shadow_color',
            field=models.CharField(blank=True, help_text='Color de la sombra del botón, ej: #000000', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='button_shadow_opacity',
            field=models.FloatField(default=1.0, help_text='Opacidad de la sombra del botón (0.0 a 1.0)'),
        ),
    ]
