# Generated by Django 5.2.3 on 2025-07-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0015_profile_button_background_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='font_family',
            field=models.CharField(blank=True, default='font-inter', help_text='Clase CSS de la fuente seleccionada', max_length=100, null=True),
        ),
    ]
