# Generated by Django 5.2.3 on 2025-07-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0016_profile_font_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='background_preference',
            field=models.CharField(default='color', help_text="Preferencia de fondo: 'image' o 'color'", max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_overlay',
            field=models.CharField(default='none', help_text="Superposición de imagen: 'none', 'dark', o 'light'", max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
