# Generated by Django 4.2.5 on 2024-01-XX XX:XX

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0017_link_clicks_profile_background_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='covers/'),
        ),
    ]