# Generated by Django 4.2.5 on 2024-01-XX XX:XX

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0018_profile_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('github', 'GitHub'), ('discord', 'Discord'), ('twitch', 'Twitch'), ('spotify', 'Spotify'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest'), ('behance', 'Behance'), ('dribbble', 'Dribbble'), ('reddit', 'Reddit'), ('email', 'Email'), ('website', 'Website'), ('other', 'Other')], max_length=20)),
                ('username', models.CharField(help_text='Username o ID de usuario', max_length=100)),
                ('url', models.URLField(help_text='URL completa del perfil social')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_icons', to='links.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='socialicon',
            unique_together={('profile', 'social_type')},
        ),
    ]