# Generated by Django 5.2.3 on 2025-07-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0019_socialicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='animations',
            field=models.JSONField(blank=True, default=list, help_text='Configuración de animaciones del perfil'),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_css',
            field=models.TextField(blank=True, default='', help_text='CSS personalizado para el perfil'),
        ),
    ]
