# Generated by Django 5.2.3 on 2025-07-23 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0020_profile_animations_profile_custom_css'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=100)),
                ('time_range', models.CharField(max_length=10)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_cache', to='links.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'cache_key', 'time_range'], name='links_analy_profile_3d4ff3_idx'), models.Index(fields=['expires_at'], name='links_analy_expires_a0849e_idx')],
                'unique_together': {('profile', 'cache_key', 'time_range')},
            },
        ),
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablet', 'Tablet')], max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_clicks', to='links.link')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_link_clicks', to='links.profile')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['link', '-timestamp'], name='links_linkc_link_id_5868a4_idx'), models.Index(fields=['profile', '-timestamp'], name='links_linkc_profile_225678_idx'), models.Index(fields=['timestamp'], name='links_linkc_timesta_114dcd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablet', 'Tablet')], max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='links.profile')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['profile', '-timestamp'], name='links_profi_profile_8c8342_idx'), models.Index(fields=['timestamp'], name='links_profi_timesta_ce6e13_idx')],
            },
        ),
    ]
