# Generated by Django 5.2.3 on 2025-07-24 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0022_socialIconclick'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='socialiconclick',
            new_name='links_socia_social__d8be08_idx',
            old_name='links_socia_social__0b7e6c_idx',
        ),
        migrations.RenameIndex(
            model_name='socialiconclick',
            new_name='links_socia_profile_3e3b9c_idx',
            old_name='links_socia_profile_d4e3a7_idx',
        ),
        migrations.RenameIndex(
            model_name='socialiconclick',
            new_name='links_socia_timesta_504285_idx',
            old_name='links_socia_timesta_4f8c1a_idx',
        ),
    ]
