# Generated by Django 5.2.3 on 2025-07-29 00:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timehub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('annual_vacation_days', models.PositiveIntegerField(default=30)),
                ('work_days', models.JSONField(default=list)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['country', 'date']},
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accumulated_vacation_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Días de vacaciones acumulados de años anteriores', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='holiday',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='timehub.country'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timehub.country'),
        ),
    ]
