# Generated by Django 5.2.3 on 2025-07-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timehub', '0002_country_alter_holiday_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='leave_balance_days',
        ),
        migrations.AddField(
            model_name='country',
            name='max_bereavement_days',
            field=models.PositiveIntegerField(default=3, help_text='Días máximos por luto'),
        ),
        migrations.AddField(
            model_name='country',
            name='max_maternity_days',
            field=models.PositiveIntegerField(default=98, help_text='Días máximos de licencia por maternidad'),
        ),
        migrations.AddField(
            model_name='country',
            name='max_paternity_days',
            field=models.PositiveIntegerField(default=10, help_text='Días máximos de licencia por paternidad'),
        ),
        migrations.AddField(
            model_name='country',
            name='max_personal_days',
            field=models.PositiveIntegerField(default=5, help_text='Días máximos de permiso personal'),
        ),
        migrations.AddField(
            model_name='country',
            name='max_sick_days',
            field=models.PositiveIntegerField(default=30, help_text='Días máximos por enfermedad'),
        ),
    ]
