# Generated by Django 5.2.3 on 2025-07-30 14:24

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timehub', '0004_role_userprofile_phone_userprofile_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='leave_attachments/'),
        ),
    ]
