# Generated by Django 5.2.3 on 2025-07-31 20:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timehub', '0007_sync_existing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='timehub.country'),
        ),
        migrations.AddField(
            model_name='project',
            name='approved_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas aprobadas para el proyecto', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto del proyecto', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Prioridad del proyecto', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('FIXED_PRICE', 'Fixed Price'), ('TIME_MATERIAL', 'Time & Material'), ('RETAINER', 'Retainer')], help_text='Tipo de proyecto', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectfollowup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='projectfollowup',
            index=models.Index(fields=['project', 'follow_up_date'], name='timehub_pro_project_9c2448_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfollowup',
            index=models.Index(fields=['status'], name='timehub_pro_status_400eea_idx'),
        ),
    ]
